### ISSUE TITLE
[aur-auto-vote] Error on login (git ver. r150.3a626c5-1)

### ISSUE THREAD

**Issue by koyuch** [cryzed/bin#16]
```sh
❯ aur-auto-vote username
Password: 
Traceback (most recent call last):
  File "/usr/bin/aur-auto-vote", line 129, in <module>
    main(arguments)
  File "/usr/bin/aur-auto-vote", line 81, in main
    voted_packages = tuple(p.name for p in sorted(get_voted_packages(session)))
  File "/usr/bin/aur-auto-vote", line 52, in get_voted_packages
    package = Package(*(c.get_text(strip=True) for c in row.select(':scope > td')[1:]))
TypeError: Package.__new__() takes 9 positional arguments but 10 were given
```

**Comment by ftapajos** [comment]
I had this same problem with r152.5559c23-1

**Comment by koyuch** [comment]
Thank you :+1: That was fast. Works as expected
