### ISSUE TITLE
beautifulsoup update breaks aur-auto-vote

### ISSUE THREAD

**Issue by xzz53** [cryzed/bin#7]
After recent bs4 update (4.6.3-1 -> 4.7.1-1) aur-auto-vote stopped functioning:
```
Traceback (most recent call last):
  File "/usr/bin/aur-auto-vote", line 127, in <module>
    main(arguments)
  File "/usr/bin/aur-auto-vote", line 86, in main
    voted_packages = tuple(p.name for p in sorted(get_voted_packages(session)))
  File "/usr/bin/aur-auto-vote", line 50, in get_voted_packages
    package = Package(*(c.get_text(strip=True) for c in row.select('> td')[1:]))
  File "/usr/lib/python3.7/site-packages/bs4/element.py", line 1376, in select
    return soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/usr/lib/python3.7/site-packages/soupsieve/__init__.py", line 108, in select
    return compile(select, namespaces, flags).select(tag, limit)
  File "/usr/lib/python3.7/site-packages/soupsieve/__init__.py", line 59, in compile
    return cp._cached_css_compile(pattern, namespaces, flags)
  File "/usr/lib/python3.7/site-packages/soupsieve/css_parser.py", line 192, in _cached_css_compile
    CSSParser(pattern, flags).process_selectors(),
  File "/usr/lib/python3.7/site-packages/soupsieve/css_parser.py", line 894, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/usr/lib/python3.7/site-packages/soupsieve/css_parser.py", line 778, in parse_selectors
    sel, m, has_selector, selectors, relations, is_pseudo, index
  File "/usr/lib/python3.7/site-packages/soupsieve/css_parser.py", line 614, in parse_combinator
    "The combinator '{}' at postion {}, must have a selector before it".format(combinator, index)
SyntaxError: The combinator '>' at postion 0, must have a selector before it
```

I believe this bs4 change is relevant:

>  4.7.0 (20181231)
>  Beautiful Soup's CSS Selector implementation has been replaced by a
>   dependency on Isaac Muse's SoupSieve project (the soupsieve package
>   on PyPI). The good news is that SoupSieve has a much more robust and
>   complete implementation of CSS selectors, resolving a large number
>   of longstanding issues.

**Comment by facelessuser** [comment]
I am the author of SoupSieve, which replaces the old BeautifulSoup `select` implementation. I am temporarily doing occasional searches for issues with `soupsieve` to help in the transition.

Soup Sieve tries to follow the CSS spec as best as is possible. In CSS, you can't just use `> td`.  A selector must come before `>`.  The old select implementation in Beautiful Soup used to allow this, I'm not sure if on purpose or not, but it isn't valid CSS. To get the same behavior, you'd have to use the CSS pseudo-class `:scope`: `:scope > td`.

This should fix the issue.

**Comment by cryzed** [comment]
Thanks for letting me know, this should be fixed. And thank you @facelessuser for the new CSS selector implementation!
